version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /app
    environment:
      APACHE_LOG_DIR: /alogs
    volumes:
      - ./app:/app
      - ./docker/php/logs:/alogs
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: syfharmonia
    ports:
      - "3307:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db